# lib/xai/proto/** is generated by `mix proto.generate` and gitignored —
# intentionally excluded here rather than reformatted/linted as our own code.
[
  inputs: [
    "mix.exs",
    "{config,test}/**/*.{ex,exs}",
    "lib/*.ex",
    "lib/xai/*.ex",
    "lib/mix/**/*.ex"
  ]
]
